version: '1'

services:
  namenode:
    image: apache/hadoop:3.4
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
      - ./:/opt/hadoop/project   
    ports:
      - "9870:9870"
      # - "9000:9000"
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.2

  datanode1:
    image: apache/hadoop:3.4
    container_name: datanode1
    hostname: datanode1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_datanode1:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.3

  datanode2:
      image: apache/hadoop:3.4
      container_name: datanode2
      hostname: datanode2
      user: root
      environment:
        - HADOOP_HOME=/opt/hadoop
      volumes:
        - ./hadoop_datanode2:/opt/hadoop/data/dataNode
        - ./hadoop_config:/opt/hadoop/etc/hadoop
        - ./init-datanode.sh:/init-datanode.sh
      depends_on:
        - namenode
      command: [ "/bin/bash", "/init-datanode.sh" ]
      networks:
        hdfs_network:
          ipv4_address: 172.20.0.4

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      SPARK_MODE: master
      PATH: /opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    command: ["--host", "spark-master"]
    ports:
      - "8080:8080"     # Web UI
      - "7077:7077"     # RPC
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.10
    volumes:
      - ./hadoop_config:/opt/spark/conf      # So Spark sees core-site.xml and hdfs-site.xml
      - ./:/opt/workspace                    #  spark_app.py 

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    environment:
      SPARK_MODE: worker
      PATH: /opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker"]
    command: ["spark://spark-master:7077"]
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.11
    volumes:
      - ./hadoop_config:/opt/spark/conf
      - ./:/opt/workspace

networks:
  hdfs_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16